apps/polls/urls.py
from django.urls import path
from . import views

# 设置tag 标签 URL的命名空间
# {% url 'pons:detail' question.id %}
app_name = 'pons'

urlpatterns = [
    path('', views.index, name='index'),
    path('home', views.home, name='home'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results', views.results, name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

django_examples/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # 加入 blog app 的 urls
    path(r'blog/', include('apps.blog.urls')),
    # 加入 polls app 的 urls
    path(r'polls/', include('apps.polls.urls'))
]+  debug_toolbar_urls()

apps/polls/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone

from common.util import utils


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    published_date = models.DateTimeField('date published')

    __str__ = lambda self: f"title: {self.question_text}, date: {self.published_date}"

    @admin.display(
        boolean=True,
        ordering="published_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        return self.published_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return utils.object_to_string(self)

apps/polls/views.py
# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse

from apps.polls.models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('-published_date')[:5]
    # content = ", ".join([q.question_text for q in latest_question_list])

    template = loader.get_template('polls/index.html')
    context = {"latest_question_list": latest_question_list}

    return HttpResponse(template.render(context, request))

def home(request):
    latest_question_list = Question.objects.order_by('-published_date')[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {"question": question, "error_message": "You didn't select a choice.",})
    else:
        selected_choice.votes += 1
        # selected_choice.votes = F("votes") + 1
        selected_choice.save()

    return HttpResponseRedirect(reverse("pons:results", args=(question.id, )))

templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票</title>
</head>
<body>
    <form action="{% url 'pons:vote' question.id %}" method="post">
        <!-- 跨域防御控制 -->
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>
</html>

templates/polls/index.html
<!-- 模板标签会生成静态文件的绝对路径 -->
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li>URL: <a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
                <!-- polls.urls 模块中的 path() 函数中定义了 name 参数，通过使用 { % url % } 模板标签来定位 detail的URL，并传递参数 -->
                <li>Tag: <a href="{% url 'pons:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>
</html>

templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>result</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    
    <a href="{% url 'pons:detail' question.id %}">Vote again?</a>
</body>
</html>